### PR TITLE
Fix bug where "--colors" arg is added everytime an user executes a test.

### LINKED ISSUE #45: Option "--color=always" is added recursivelly at console output at each "rerun last test'
After the v4.1.0 the **--colors=always** option started to be default. At my config I used to use the **phpunit.colors** config setted as **--colors=always** without problems. Now, every time that I rerun some phpunit test one more "--color-always" is added to the console output.

## Repro
1. Set the config **phpunit.colors** with the value **--colors=always**
2. Run any test
3. Use the command to rerun last test

## Outcome
4. Check that every time you rerun any test one more "--colors=always" is added to your console output

## Expected outcome
The console shouldn't modify its output, like it was at previous versions. You can fix it by removing the *--color-always* setted in your *phpunit.colors* config (I just did it and works well)

## Logs / output / settings

console-output

settings.json
```json
"phpunit.command": "docker-compose exec php",
"phpunit.phpunit": "vendor/bin/phpunit",
"phpunit.paths": {
  "${workspaceFolder}": "/var/www/app"
}
```

Just an observation: I use the extension with docker

| **Environment** | **Values** |
| --- | --- |
| *Extension version* | v4.1.0 |
| *Operating system* | Ubuntu 18.04 |

### PR DESCRIPTION
**Pull request by 9brada6**
Fixes #45

### CODE REVIEW

**Comment by roelofr** [comment]
Can we get a merge on this? I'm kind-of done with scrolling down 5 screens filled with `--colors=always`, just to get to the errors.

**Comment by RomainGoncalves** [comment]
> Can we get a merge on this? I'm kind-of done with scrolling down 5 screens filled with `--colors=always`, just to get to the errors.

I would second that. Please!

**Comment by elonmallin** [comment]
Awesome, thanks for the PR! And sorry for the wait, I'm just back from vacation and not using PHP privately anymore so I'm not so quick here.

**Comment by elonmallin** [comment]
Published a new version with the fix, thanks again for the PR! It should show up in the marketplace soon and is available on github here too: https://github.com/elonmallin/vscode-phpunit/releases/tag/v4.1.1

**Comment by RomainGoncalves** [comment]
Thanks a lot

**Comment by RomainGoncalves** [comment]
Thanks a lot

**Pull request merged**
