### PR TITLE
Support selecting test

### PR DESCRIPTION
**Pull request by eric-hansen**
Allows user to choose which test to run within the class (no support for inherited classes as this simply reads the currently open test).

I don't know how to make GIFs like done in rest of README.

### CODE REVIEW

**Comment by elonmallin** [comment]
Hi Eric. Thanks for the pull request. I had a quick look at the changes and they seem quite ok.

However, I am not sure that I want to merge the request as it is. I would like to avoid a config option and keep it more simple.
I think it would be better that if you run phpunit from any line that is not the **class line** of **function line** we could show this quick pick window. But add the option to run the whole class in the list too.
The order would be:
```
Closest function above cursor
class CLASSNAME
function FUNCTIONNAME
function...
```

What do you think about that?

I would even prefer to run the test function by default if the cursor is inside the function but I think the parsing for this could be a bit too complex and error prone. And then only show the quick pick window if the cursor is in between functions and not on the **class line** or **function line**.

**Comment by eric-hansen** [comment]
I would like to explain why I did things a certain way and if you still feel the same then I can work on implementing what you are asking for.

> I would like to avoid a config option and keep it more simple.

This was simply to keep backwards compatibility with how it was before these changes.  Really by default it requires setting this to false to use this new feature.

As for your structure idea of closest/class/rest I like that.

> I would even prefer to run the test function by default if the cursor is inside the function but I think the parsing for this could be a bit too complex and error prone.

This is something I considered when writing this code.  However, I leaned against it simply because of the use case where you might be in a different test (comparing or something) and then keep running the incorrect test.  This I do feel should be a setting if so chosen to follow this approach.

> And then only show the quick pick window if the cursor is in between functions and not on the class line or function line.

The parsing for *this* would be too difficult.  Not impossible but I feel would be easy to break.

**Comment by elonmallin** [comment]
I understand the backwards compatibility argument but I do think it would be better to get the quick pick window if you don't explicitly have the cursor directly on the class or function line. It's a better experience for everyone than how it is now so it would be cool to just have it by default. How I implemented it now is not the best way it was partly made because of simplicity.

The order of closest/class/rest should be good I think too.

The other two things you mentioned we are on the same page with. I think it would be too complex and error prone.

If you could do some of this it would be awesome, otherwise I can get to it probably next week. Either way you can leave the version bumping to 2.0.0 and update the readme with these new changes to me.

**Comment by eric-hansen** [comment]
I think I was misunderstanding your suggestion originally, so let me make sure we're on the same page.

If a user is either on a line that defines a function or test, automatically run the test accordingly.  If the user is in any other scenario, show the quick pick window.

Am I correct?

**Comment by elonmallin** [comment]
If a user is on:
`public class MyClass...`
or
`public function testSomething()...`
we run the whole class or the test function directly.
If he's in between functions or inside a function or anywhere else really, we show the quick pick window.

I'm not sure what your distinction between function and test is?

**Comment by eric-hansen** [comment]
Sorry meant to say class or function, hah.  Okay so yeah we're on the same page.  I can put up a fix soon on this then.  Is that the only change you want to make?

I know you mentioned about the setting, I believe this would nullify the need for said setting.

**Comment by elonmallin** [comment]
Ah okey =P Yea that's it.

Exactly, the setting wouldn't be needed anymore.

**Comment by eric-hansen** [comment]
Alright believe everything is done as suggested.  Did some refactoring of various things as well to make it a little cleaner.

**Comment by elonmallin** [comment]
Thanks, I'll test it and push an update probably next week.

**Pull request merged**
